export enum CommentComplainsEnum {
  UNWANTED_AD_OR_SPAM,
  PORNOGRAPHY_OR_EXPLICIT_SEXUAL_CONTENT,
  CHILD_ABUSE,
  HOSTILE_LANGUAGE_OR_EXPLICIT_VIOLENCE,
  AGGRESSIVE_BEHAVIOR_OR_THREATS,
  MISLEADING_INFORMATION,
}
